//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhi
    {
        public int ID { get; set; }
        public string Ten { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public string DonViTinh { get; set; }
    }
}
