//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNhaTro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuePhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuePhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.TraPhongs = new HashSet<TraPhong>();
        }
    
        public int ID { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
        public Nullable<System.DateTime> NgayThue { get; set; }
        public Nullable<System.DateTime> NgayNhanCoc { get; set; }
        public Nullable<int> KhachHangID { get; set; }
        public Nullable<int> PhongID { get; set; }
        public Nullable<bool> TrangThaiThanhToan { get; set; }
        public Nullable<bool> TrangThaiTraPhong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phong Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TraPhong> TraPhongs { get; set; }
    }
}
